'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import SideNav from '@/components/SideNav';
import { Suspense, useState } from "react";
import { Header } from "@/components/Header";
import Login from "@/components/Login";
import { useUserStore } from "@/store/userStore";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = useUserStore(state => state.isLogin);
  // const unsub3 = useUserStore.subscribe(
  //   (state) => console.log(998, state),
  // )
  
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          {isLogin ? (
            <div className="flex h-screen w-screen">
              <SideNav />
              <div className="flex flex-col flex-auto bg-[#f8f9fd]">
                <Suspense fallback={<h6 className='text-center ltr'>📡 Loading data please wait ... </h6>}>
                  <Header />
                  <div className="bg-[#fff] rounded-lg m-5 p-8 flex-auto">
                    {children}
                  </div>
                </Suspense>
              </div>
            </div>
          ): (
            <Login />
          )}
        </Providers>
      </body>
    </html>
  );
}
